### ISSUE TITLE
Explore using sync.Map from go 1.9

### ISSUE THREAD

**Issue by schmidtw** [Comcast/talaria#22]
The `sync.Map` construct in the golang STL may be a good match for Talaria's connected devices.  We should:

1. Profile what we have
1. Convert to using `sync.Map`
1. Profile with `sync.Map`
1. See if the code beauty and performance are awesome & merge or trash

**Comment by johnabass** [comment]
This has been done.  There's little difference in performance, and it makes the code more complex due to a lot of casting.

A better approach would be a truly sharded map.
