### ISSUE TITLE
The metric xmidt_talaria_device_count is inconsistent with service discovery metrics

### ISSUE THREAD

**Issue by mykllterry** [Comcast/talaria#66]
Prometheus Query: sort((xmidt_talaria_device_count{instance=~"talaria-prod-.+", stage="prod", region="hoa"}))

This query shows result from all 126 talaria in the region.  Three talaria: 
talaria-prod-00101-184-204-4um
talaria-prod-00101-184-204-adb
talaria-prod-00101-184-204-hpf

appear with connected devices but do not appear in the service discovery metrics. Kind of looks like these may be orphaned devices?

**Comment by mykllterry** [comment]
May be related...
10/30-31 during traffic shaping 29 talaria were shutdown bringing the expected value for talaria in the HOA region down to 97. Eight talaria kept reporting 125 (previous value should have been 126) We decided to restart those 8 talaria and it was noticed a consul thread was also dead and needed restarted. The 8 were: 96s,k4x,ov3,qeb,r98,x68,ks9,vue

**Comment by kcajmagic** [comment]
Closing as consul SD has been fixed.
