### ISSUE TITLE
Add Convey Hardware Metric

### ISSUE THREAD

**Issue by schmidtw** [Comcast/talaria#68]
We would like a metric gauge that shows the count of connections per convey hardware field (`hw-model`).

If there is not valid convey header `hw-model` the value `invalid` should be used.

As connections are made, the gauge+`hw-model` label will be incremented.
As connections are disconnected/closed, the gauge+`hw-model` label will be decremented.

**Comment by kcajmagic** [comment]
PR #72 completes this.
