### ISSUE TITLE
Emit online/offline events 

### ISSUE THREAD

**Issue by schmidtw** [Comcast/talaria#80]
When a device connects to Talaria it should emit a WRP [Simple Event](https://github.com/Comcast/wrp-c/wiki/Web-Routing-Protocol#simple-event-definition)s as defined below and apply the routing rules defined in the `event-map` configuration.

## Online

```json
{
    "msg_type": "4",
    "source": "{talaria-fqdn}",
    "dest": "event:device-status/{device-id}/online",
    "content_type": "json",
    "partner_ids": [ "{partner-id}" ],
    "metadata": {
        "/boot-time" : "{boot-time}",
        "/hw-model" : "{hw-model}",
        "/hw-manufacturer" : "{hw-manufacturer}",
        "/hw-serial-number" : "{hw-serial-number}",
        "/hw-last-reboot-reason" : "{last-reboot-reason}",
        "/fw-name" : "{fw-name}",
        "/last-reconnect-reason" : "{last-reconnect-reason}",
        "/protocol" : "{parodus-version}",
        "/trust" : "{trust}",
        "/compliance" : "{compliance}",
    },
    "payload": {
        "id": "{device-id}",
        "ts": "2018-11-21T21:19:02.614191735Z",
    }
}
```
## Offline

```json
{
    "msg_type": "4",
    "source": "{talaria-fqdn}",
    "dest": "event:device-status/{device-id}/offline",
    "content_type": "json",
    "partner_ids": [ "{partner-id}" ],
    "metadata": {
        "/boot-time" : "{boot-time}",
        "/hw-model" : "{hw-model}",
        "/hw-manufacturer" : "{hw-manufacturer}",
        "/hw-serial-number" : "{hw-serial-number}",
        "/hw-last-reboot-reason" : "{last-reboot-reason}",
        "/fw-name" : "{fw-name}",
        "/last-reconnect-reason" : "{last-reconnect-reason}",
        "/protocol" : "{parodus-version}",
        "/trust" : "{trust}",
        "/compliance" : "{compliance}",
    },
    "payload": {
        "id": "{device-id}",
        "ts": "2018-11-21T21:19:02.614191735Z",
        "bytes-sent": 0,
        "messages-sent": 1,
        "bytes-received": 0,
        "messages-received": 0,
        "connected-at": "2018-11-21T21:19:02.614191735Z",
        "up-time": "16m46.6s",
        "reason-for-closure": "ping miss"
    }
}
```

## Description of most fields

* `{talaria-fqdn}` - The fully qualified domain name for the Talaria sending this event (example: `dns:talaria-1234.example.com`).
* `{device-id}` - The device id of the device that connected (example: `mac:112233445566`)
* `{partner-id}` - The partner-id of the device that connected (from authorization JWT).
* `{boot-time}` - The boot time of the device that connected (from convey header).
* `{hw-model}` - The hardware model of the device that connected (from convey header).
* `{hw-manufacturer}` - The hardware manufacturer of the device that connected (from convey header).
* `{hw-serial-number}` - The hardware serial number of the device that connected (from convey header).
* `{last-reboot-reason}` - The last reboot reason of the device that connected (from convey header).
* `{fw-name}` - The firmware name of the device that connected (from convey header).
* `{last-reconnect-reason}` - The last reconnection reason of the device that connected (from convey header).
* `{parodus-version}` - The parodus version of the device that connected (from convey header).
* `{trust}` - The trust value of the device that connected (from authorization JWT).
* `{compliance}` - How well the client complies with sending the required information. [Details](https://github.com/Comcast/talaria/issues/80#issuecomment-444585330)
* `ts` - The current timestamp on the Talaria machine.
* `connected-at` - The timestamp on the Talaria machine when the device first connected.
* `reason-for-closure` - The reason that Talaria closed the connection.
* `up-time` - The total duration of time the connection was open from Talaria's perspective.

If a value listed above is unknown the item may be set to empty or omitted completely.

**Comment by johnabass** [comment]
A few questions:

1. Currently, `talaria` drops outbound messages when upstream servers (e.g. caduceus) are unable to keep up.  What happens when `talaria` drops a connect or disconnect event?
2. Under heavy load, `talaria` cannot preserve ordering of events due to barging.  That means that a disconnect event can be sent before a connect event.  What happens in that situation?
3. What happens when a device emits a malformed `convey` header or no such header at all?

**Comment by schmidtw** [comment]
* At a minimum, all drops need to be accounted for in metrics.
* All events are treated equally, if the event drops, it drops the exact same way as any other event.
* The ordering of events is *never* assured and all consuming services *must* take that into account.  Talaria *may* send events out of order.


If missing or malformed, that's a great question.  I think we should add metadata that describes the state of the device (like `trust`).  I propose adding `/compliance` with the enumeration:
* `full` - all needed information has been provided
* `missing-convey` - missing the convey header
* `invalid-convey` - invalid convey header
* `convey-missing-fields` - a convey header that does not meet our requirements

**Comment by schmidtw** [comment]
Clarification: The payload shall be JSON, regardless of the encoding of the WRP.

**Comment by schmidtw** [comment]
This has been completed.
