### ISSUE TITLE
malformed online/offline events

### ISSUE THREAD

**Issue by kristinaspring** [Comcast/talaria#89]
Codex is receiving some online/offline events either without the `ts` key in the payload (most likely option) or where the value for the `ts` key isn't a string.

**Comment by johnabass** [comment]
Do we have an example message?

Also, I'm wondering if some talarias haven't been updated.  The master branch doesn't have any logic branches where `ts` wouldn't be the timestamp.

**Comment by kristinaspring** [comment]
After getting more verbose logs, the events were found to not be coming from talaria.  Closing this issue.
